export default {
  log: [
    {
      id: 0,
      title: "ATACAMA-1TG1A_TG1A+0.5TV1_GNL_INFLEX",
      eo: "DN",
      co: "FS",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 4.9,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 1,
      title: "ATACAMA-1TG1AB_TG1A+TG1B+TV1_GNL_INFLEX",
      eo: "FE",
      co: "FS",
      io: "SIF",
      outOfService: true,
      unavailable: true,
      lim: "",
      limitation: false,
      cv: 4.9,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 2,
      title: "ATACAMA-1TG1B_TG1B+0.5TV1_GNL_INFLEX",
      eo: "DN",
      co: "FS",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 4.9,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 3,
      title: "ATACAMA-2TG2A_TG2A+0.5TV2_GNL_INFLEX",
      eo: "LP",
      co: "FS",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "LP",
      limitation: true,
      cv: 4.9,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 4,
      title: "ATACAMA-2TG2AB_TG2A+TG2B+TV2_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "CC",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 4.9,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 5,
      title: "ATACAMA-2TG2B_TG2B+0.5TV2_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 4.9,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 6,
      title: "VINALES_BL1_COGEN",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: true,
      unavailable: false,
      lim: "LF",
      limitation: true,
      cv: 0,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 7,
      title: "TOCOPILLA-TG3_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: true,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 1.1,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 8,
      title: "CMPCCORDILLERA_BL1_COGEN",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 1.36,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 9,
      title: "KELAR-TG12_TG1+TG2+TV1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "LC",
      limitation: true,
      cv: 1.95,
      instructedGx: 20,
      realGx: 20,
      edit: true
    },
    {
      id: 10,
      title: "NEHUENCO-2_TG1+TV1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: true,
      unavailable: true,
      lim: "",
      limitation: false,
      cv: 2.44,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 11,
      title: "CANDELARIA-1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 2.75,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 12,
      title: "CANDELARIA-2_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "RO",
      limitation: true,
      cv: 2.75,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 13,
      title: "SANISIDRO-1_TG1+TV1+FA1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 2.83,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 14,
      title: "NEHUENCO-1_TG1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 2.88,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 15,
      title: "NEHUENCO-1_TG1+TV1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 2.91,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 16,
      title: "NEHUENCO-9B_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 2.91,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 17,
      title: "NEHUENCO-2_TG1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: true,
      lim: "",
      limitation: false,
      cv: 3.27,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 18,
      title: "KELAR-TG1_TG1+0.5TV_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "LF",
      limitation: true,
      cv: 3.66,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 19,
      title: "KELAR-TG2_TG2+0.5TV_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 3.66,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 20,
      title: "NUEVARENCA_TG1+TV1_GNL_INFLEX",
      eo: "N",
      co: "CB",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 3.77,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 21,
      title: "QUINTERO-1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 3.81,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 22,
      title: "QUINTERO-2_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 3.81,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 23,
      title: "SANISIDRO-2_TG1+TV1_FSTVU_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 3.84,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 24,
      title: "PETROPOWER_PET",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 3.95,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 25,
      title: "VALDIVIA_BL1_COGEN_EUCA",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: true,
      unavailable: true,
      lim: "",
      limitation: false,
      cv: 0,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 26,
      title: "VALDIVIA_BL1_COGEN_PINO",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 0,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 27,
      title: "VALDIVIA_BL1+BL2_COGEN_EUCA",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 0,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 28,
      title: "VALDIVIA_BL1+BL2_COGEN_PINO",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "RO",
      limitation: true,
      cv: 0,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 29,
      title: "SANISIDRO-2_TG1+TV1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: true,
      lim: "",
      limitation: false,
      cv: 4.31,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 30,
      title: "TALTAL-1_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: false,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 4.69,
      instructedGx: 20,
      realGx: 20
    },
    {
      id: 31,
      title: "TALTAL-2_GNL_INFLEX",
      eo: "N",
      co: "MT",
      io: "OT",
      outOfService: true,
      unavailable: false,
      lim: "",
      limitation: false,
      cv: 4.69,
      instructedGx: 20,
      realGx: 20
    }
  ],
  opLog: {
    showAddForm: false
  },
  movement: {
    selection: [],
    activeStep: 0
  },
  facilities: {
    filters: [],
    list: [
      { id: 0, title: "Aguas Blancas", regionId: 1, disabled: false },
      { id: 1, title: "Andes", regionId: 1, disabled: true },
      { id: 2, title: "Andina", regionId: 2, disabled: false },
      { id: 3, title: "Angamos", regionId: 3, disabled: false },
      { id: 4, title: "Angostura", regionId: 1, disabled: false },
      { id: 5, title: "Antilhue", regionId: 1, disabled: false },
      { id: 6, title: "Antuco", regionId: 1, disabled: false },
      { id: 7, title: "Arauco", regionId: 1, disabled: true },
      { id: 8, title: "Arica", regionId: 0, disabled: false },
      { id: 9, title: "Atacama", regionId: 10, disabled: false },
      { id: 10, title: "Bocamina", regionId: 10, disabled: false },
      { id: 11, title: "Calle Calle", regionId: 10, disabled: false },
      { id: 12, title: "Campiche", regionId: 10, disabled: false },
      { id: 13, title: "Candelaria", regionId: 10, disabled: false },
      { id: 14, title: "Canutillar", regionId: 10, disabled: false },
      { id: 15, title: "Cardones", regionId: 10, disabled: false },
      { id: 16, title: "Celco", regionId: 10, disabled: false },
      { id: 17, title: "Cementos Bio Bio", regionId: 10, disabled: true },
      { id: 18, title: "Cenizas", regionId: 10, disabled: false },
      { id: 19, title: "Cerro Pabellon", regionId: 10, disabled: false },
      { id: 20, title: "Chapiquiña", regionId: 0, disabled: false },
      { id: 21, title: "El Aguila", regionId: 0, disabled: false },
      { id: 22, title: "Pampa Camarones", regionId: 0, disabled: false }
    ]
  }
};
