export const CREATE_ADD_MOVEMENT_FILTER_REQUEST =
  "CREATE_ADD_MOVEMENT_FILTER_REQUEST";
export const CREATE_ADD_MOVEMENT_FILTER_SUCCESS =
  "CREATE_ADD_MOVEMENT_FILTER_SUCCESS";
export const CREATE_ADD_MOVEMENT_FILTER_FAILURE =
  "CREATE_ADD_MOVEMENT_FILTER_FAILURE";
export const REMOVE_ADD_MOVEMENT_FILTER_REQUEST =
  "REMOVE_ADD_MOVEMENT_FILTER_REQUEST";
export const REMOVE_ADD_MOVEMENT_FILTER_SUCCESS =
  "REMOVE_ADD_MOVEMENT_FILTER_SUCCESS";
export const REMOVE_ADD_MOVEMENT_FILTER_FAILURE =
  "REMOVE_ADD_MOVEMENT_FILTER_FAILURE";
export const SHOW_ADD_MOVEMENT_FORM_REQUEST = "SHOW_ADD_MOVEMENT_FORM_REQUEST";
export const SHOW_ADD_MOVEMENT_FORM_SUCCESS = "SHOW_ADD_MOVEMENT_FORM_SUCCESS";
export const SHOW_ADD_MOVEMENT_FORM_FAILURE = "SHOW_ADD_MOVEMENT_FORM_FAILURE";
export const UPDATE_ADD_MOVEMENT_FACILITY_REQUEST =
  "UPDATE_ADD_MOVEMENT_FACILITY_REQUEST";
export const UPDATE_ADD_MOVEMENT_FACILITY_SUCCESS =
  "UPDATE_ADD_MOVEMENT_FACILITY_SUCCESS";
export const UPDATE_ADD_MOVEMENT_FACILITY_FAILURE =
  "UPDATE_ADD_MOVEMENT_FACILITY_FAILURE";
export const UPDATE_ADD_MOVEMENT_STEPPER_REQUEST =
  "UPDATE_ADD_MOVEMENT_STEPPER_REQUEST";
export const UPDATE_ADD_MOVEMENT_STEPPER_SUCCESS =
  "UPDATE_ADD_MOVEMENT_STEPPER_SUCCESS";
export const UPDATE_ADD_MOVEMENT_STEPPER_FAILURE =
  "UPDATE_ADD_MOVEMENT_STEPPER_FAILURE";
